!ArenaConfig
arenas:
  -1: !Arena
    blackouts: []
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3
        x: 35
        y: 0
        z: 5
      rotations: []
      sizes: []
    - !Item
      name: GoodGoal
      positions:
      - !Vector3
        x: 5
        y: 0
        z: 35
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors:
      - !RGB {r: 100, g: 100, b: 204 }
      name: Wall
      positions:
      - !Vector3
        x: 30
        y: 0
        z: 25
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 10
        y: 5
        z: 1
    - !Item
      colors:
      - !RGB {r: 4, g: 200, b: 204 }
      name: Wall
      positions:
      - !Vector3
        x: 10
        y: 0
        z: 10
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 10
        y: 5
        z: 1
    - !Item
      colors:
      - !RGB {r: 100, g: 100, b: 100 }
      name: Wall
      positions:
      - !Vector3
        x: 10
        y: 0
        z: 28
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 8
        y: 5
        z: 1
    - !Item
      colors:
      - !RGB {r: 200, g: 200, b: 204 }
      name: Wall
      positions:
      - !Vector3
        x: 20
        y: 0
        z: 10
      rotations:
      - 90
      sizes:
      - !Vector3
        x: 15
        y: 5
        z: 1
    - !Item
      colors:
        - !RGB {r: 204, g: 0, b: 204 }
      name: Wall
      positions:
      - !Vector3
        x: 15
        y: 0
        z: 30
      rotations:
      - 90
      sizes:
      - !Vector3
        x: 15
        y: 5
        z: 1
    pass_mark: 0
    t: 250
